micronaut:
  application:
    name: pix_keymanager

#grpc:
#  server:
#    port: 50051

datasources:
  default:
    url: 'jdbc:postgresql://localhost:5432/pix_keymanager'
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 'postgres'
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true

#Mensagens
client.not.found: Cliente não foi encontrado nos registros de clientes do Itau
key.already.registered: Essa chave pix já está registrada
required.id.client: É obrigatório passar o id do cliente
required.valid.typekey: É obriatório passar um tipo de chave válido
required.valid.typeaccount: É obriatório passar um tipo de conta válido
invalid.pix.format: Formato da chave Pix não é válido
required.pix.id: É obrigatório passar o id do pix
pixkey.not.found: Chave pix não encontrada
uuid.bad.format: O valor está mal formatado

#Client
itau.api.url: http://localhost:9091/api/v1
bcb.api.url: http://localhost:8082/api/v1/pix/keys